User add
srkirve77/user_reg pull request #7
Opened 2021-05-26 08:40 UTC by srkirve77

Added add user functionality to application

2021-05-26 08:48 UTC, Santosh-Punase requested changes

2021-05-26 08:48 UTC, Santosh-Punase commented on src/server-conn/postUser.jsx
> +    if(parseInt(data.code/100)!==2) {
Pls read about htttp `status` code

2021-05-26 08:48 UTC, Santosh-Punase commented on src/add-user/adduser.jsx
> +            <AddIcon className = {classes.addbutton} />Add User
you can write test for button click

2021-05-26 08:48 UTC, Santosh-Punase commented on src/server-conn/postUser.jsx
> +    if(parseInt(data.code/100)!==2) {
hint: don't manipulate it

2021-05-26 08:50 UTC, srkirve77 commented on src/add-user/adduser.jsx
> +            <AddIcon className = {classes.addbutton} />Add User
Okay

2021-05-26 08:50 UTC, srkirve77 commented on src/server-conn/postUser.jsx
> +    if(parseInt(data.code/100)!==2) {
Okay will do it some other way

2021-05-31 09:52 UTC, Santosh-Punase approved these changes
Comments are not resolved as expected. we will discuss this in a doubt session.
Approving for now so that you can proceed.

2021-05-31 10:09 UTC, merged